name: build userscript
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - src/**
      - package.json
      - pnpm-lock.yaml

env:
  FORCE_COLOR: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "pnpm"

      - name: Get some values needed for the release
        id: release_values
        run: |
          echo "release_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - run: pnpm install --frozen-lockfile

      - name: build userscript
        env:
          BUILD_ENV: prod
          RELEASE_TAG: ${{ env.release_tag }}
        run: pnpm run build

      - name: Upload release
        run: |
          gh release upload release --clobber dist/*
          gh release edit release --title "release $RELEASE_TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ env.release_tag }}